### ISSUE TITLE
Will it support WG111v3?

### ISSUE THREAD

**Issue by SpookTheProgrammer** [MatMaul/pynetgear#108]
I will do some tests first but hope it works

**Comment by starkillerOG** [comment]
This library is for controlling a Netgear Router/Acces point.
The WG111v3 appears to be a USB ethernet adapter/client not a router or acces point.
So I don't know what you would want to do with the WG111v3?

**Comment by SpookTheProgrammer** [comment]
Thanks for the response!


man. 7. feb. 2022 kl. 13:08 skrev starkillerOG ***@***.***>:
