### ISSUE TITLE
Sponsor link

### ISSUE THREAD

**Issue by starkillerOG** [MatMaul/pynetgear#114]
@MatMaul since I curently maintain this repositry and am also planning to add more features soon.
Would it be alright with you if I add a link and button on this repositry page to my github sponsor page (https://github.com/sponsors/starkillerOG)?
(For an example see https://github.com/starkillerOG/motion-blinds where I already added those sponsor links.)

I have had some people from other projects I work on ask me if I had any way to support/sponsor, which lead me to enable the sponsor page on my github profile this week.
But since this project was setup by you and still published under your name, I want to check with you first.

**Comment by MatMaul** [comment]
Hi there, with great pleasure go ahead. I am also happy to transfer the repo under your name if you want.

**Comment by starkillerOG** [comment]
Thanks!
Transfering the repo under my name is fine with me, however I don't exactly know how to transfer a repo (also don't know if anything needs to be done to upload to pypi once the repo is transfered).

**Comment by starkillerOG** [comment]
I just merged the commit for the sponsor buttons.
