### ISSUE TITLE
Feature request: Show and edit device access

### ISSUE THREAD

**Issue by gruijter** [MatMaul/pynetgear#16]
Great work! Would it be possible to add the capability to block network access for a device? Use case would be to block my sons iPad after 10pm, or when he has been using too much traffic by watching youtube 😁

**Comment by ArneCL** [comment]
@gruijter Netgear only offers kind of a "solution" for this (i.e. [Netgear Parental Control](https://kb.netgear.com/25687/How-do-I-configure-Live-Parental-Controls-on-my-NETGEAR-router-using-the-NETGEAR-genie-app)). However, the automation you want - block MAC-Addr. XX:XX:XX:XX after 10pm or 1gb/24h is - as far as I know - not offered "out of the box" by netgear. (You might want to take a look at Fritz! devices...)

If you were talking about manually blocking devices, I don't think the SOAP API supports this - According to [Netgear](https://kb.netgear.com/24830/Configuring-Access-Control-on-Nighthawk-Wi-Fi-Router) you have to access the router's web-ui.

Please correct me if you are able to block devices using the genie-app (on android/ios) - Currently I can only see/test was is available on a WNDR3700v2!

**Comment by gruijter** [comment]
Hi @ArneCL Yes, I can definitely block devices on my R7000 via the genie app! And in my SOAP devicelist resonse I get an extra field per device showing the status of the device, i.e. " access" or " blocked". I do have to enable Access Control first in the router ( also an available setting via Genie).
So I guess it depends on the router if device blocking is available.

**Comment by gruijter** [comment]
For everybody's information: I created a javascript version of pynetgear. I included the 'Allow' or 'Block' status for the getAttachedDevices command.

https://github.com/gruijter/netgear.js/

**Comment by ArneCL** [comment]
@gruijter Thanks for the information - Seems I need to get a Nighthawk aka Stealth Router 💰 

Would it be possible for you (or anyone else) to provide a http-dump of the SOAP request/response from the genie-app to your router (when blocking/allowing a device)?

> For IOs devices this was very helpful:
> [How To Inspect IOs http-traffic](https://www.engadget.com/2011/02/21/how-to-inspect-ioss-http-traffic-without-spending-a-dime/)


Would welcome a PR for this ...

**Comment by gruijter** [comment]
Already working on it 😁. I will try to implement it in my own js version, but first neec to figure out how...

**Comment by gruijter** [comment]
So, blocking a device works in 3 steps (assuming being logged in first):
* Set router in config mode
* Send command to block/allow a device based on mac
* Set route in config_finished mode

For the first step, this is the post I captured:
```
POST http://routerlogin.net:5000/soap/server_sa/ HTTP/1.1
Host: routerlogin.net:5000
Pragma: no-cache
Cache-Control: no-cache
Accept-Language: nl-nl
User-Agent: SOAP Toolkit 3.0
Accept: */*
Content-Type: text/xml; charset=utf-8
SOAPAction: "urn:NETGEAR-ROUTER:service:DeviceConfig:1#ConfigurationStarted"
Connection: keep-alive
Connection: keep-alive
Content-Length: 604
Accept-Encoding: gzip, deflate

<?xml version="1.0" encoding="utf-8" standalone="no"?>
<SOAP-ENV:Envelope xmlns:SOAPSDK1="http://www.w3.org/2001/XMLSchema" xmlns:SOAPSDK2="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAPSDK3="http://schemas.xmlsoap.org/soap/encoding/" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
<SOAP-ENV:Header>
<SessionID>10588AE69687E58D9A00</SessionID>
</SOAP-ENV:Header>
<SOAP-ENV:Body>
<M1:ConfigurationStarted xmlns:M1="urn:NETGEAR-ROUTER:service:DeviceConfig:1">
  <NewSessionID>10588AE69687E58D9A00</NewSessionID>
</M1:ConfigurationStarted>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

and the resulting response is:
```
HTTP/1.1 200 OK
CONTENT-LENGTH: 451
CONTENT-TYPE: text/xml; charset="UTF-8"
SERVER: "OS/version" UPnP/1.0 "product/version"

<?xml version="1.0" encoding="UTF-8"?>
<soap-env:Envelope
        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"
        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
       >
 <soap-env:Body>
    <m:ConfigurationStartedResponse
        xmlns:m="urn:NETGEAR-ROUTER:service:DeviceConfig:1">
    </m:ConfigurationStartedResponse>
    <ResponseCode>000</ResponseCode>
</soap-env:Body>
</soap-env:Envelope>
```

But when I use above post data myself (using the pynetgear templates) I get a response "702" in stead of "000".

**Comment by gruijter** [comment]
This is the capture for step 2 (to allow a device, use Block to disable the device):
```
POST http://routerlogin.net:5000/soap/server_sa/ HTTP/1.1
Host: routerlogin.net:5000
Accept-Language: nl-nl
Pragma: no-cache
Accept-Encoding: gzip, deflate
User-Agent: SOAP Toolkit 3.0
Accept: text/xml
Content-Type: text/xml; charset=utf-8
SOAPAction: "urn:NETGEAR-ROUTER:service:DeviceConfig:1#SetBlockDeviceByMAC"
Connection: keep-alive
Connection: keep-alive
Content-Length: 643
Cache-Control: no-cache

<?xml version="1.0" encoding="utf-8" standalone="no"?>
<SOAP-ENV:Envelope xmlns:SOAPSDK1="http://www.w3.org/2001/XMLSchema" xmlns:SOAPSDK2="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAPSDK3="http://schemas.xmlsoap.org/soap/encoding/" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
<SOAP-ENV:Header>
<SessionID>10588AE69687E58D9A00</SessionID>
</SOAP-ENV:Header>
<SOAP-ENV:Body>
<M1:SetBlockDeviceByMAC xmlns:M1="urn:NETGEAR-ROUTER:service:DeviceConfig:1">
<NewAllowOrBlock>Allow</NewAllowOrBlock>
<NewMACAddress>A1:CB:FD:7B:B9:48</NewMACAddress>
</M1:SetBlockDeviceByMAC>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

and the response:

```
HTTP/1.1 200 OK
CONTENT-LENGTH: 449
CONTENT-TYPE: text/xml; charset="UTF-8"
SERVER: "OS/version" UPnP/1.0 "product/version"

<?xml version="1.0" encoding="UTF-8"?>
<soap-env:Envelope
        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"
        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
       >
 <soap-env:Body>
    <m:SetBlockDeviceByMACResponse
        xmlns:m="urn:NETGEAR-ROUTER:service:DeviceConfig:1">
    </m:SetBlockDeviceByMACResponse>
    <ResponseCode>000</ResponseCode>
</soap-env:Body>
</soap-env:Envelope>
```

**Comment by gruijter** [comment]
And finally, the capture for step 3:

```
POST http://routerlogin.net:5000/soap/server_sa/ HTTP/1.1
Host: routerlogin.net:5000
Accept-Language: nl-nl
Pragma: no-cache
Accept-Encoding: gzip, deflate
User-Agent: SOAP Toolkit 3.0
Accept: text/xml
Content-Type: text/xml; charset=utf-8
SOAPAction: "urn:NETGEAR-ROUTER:service:DeviceConfig:1#ConfigurationFinished"
Connection: keep-alive
Connection: keep-alive
Content-Length: 594
Cache-Control: no-cache

<?xml version="1.0" encoding="utf-8" standalone="no"?>
<SOAP-ENV:Envelope xmlns:SOAPSDK1="http://www.w3.org/2001/XMLSchema" xmlns:SOAPSDK2="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAPSDK3="http://schemas.xmlsoap.org/soap/encoding/" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
<SOAP-ENV:Header>
<SessionID>10588AE69687E58D9A00</SessionID>
</SOAP-ENV:Header>
<SOAP-ENV:Body>
<M1:ConfigurationFinished xmlns:M1="urn:NETGEAR-ROUTER:service:DeviceConfig:1">
<NewStatus>ChangesApplied</NewStatus>
</M1:ConfigurationFinished>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

and the response:

```
HTTP/1.1 200 OK
CONTENT-LENGTH: 453
CONTENT-TYPE: text/xml; charset="UTF-8"
SERVER: "OS/version" UPnP/1.0 "product/version"

<?xml version="1.0" encoding="UTF-8"?>
<soap-env:Envelope
        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"
        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
       >
 <soap-env:Body>
    <m:ConfigurationFinishedResponse
        xmlns:m="urn:NETGEAR-ROUTER:service:DeviceConfig:1">
    </m:ConfigurationFinishedResponse>
    <ResponseCode>000</ResponseCode>
</soap-env:Body>
</soap-env:Envelope>
```

**Comment by ArneCL** [comment]
@gruijter Thanks a lot for providing and reverse-engineering the requests. 
A `702` seems to be some kind of custom status-code - so these are just guesses:

- Maybe there is something going on with the session-id? (e.g. session ID used for login has to be same as used to set the router to config-mode?)

- Maybe you need to send a different SOAP-Header for authentication/login?

Already ordered a R7000 and WNR2000v5 to further investigate... 

Spoiler alert: You might also want to investigate the SOAP actions `urn:NETGEAR-ROUTER:service:DeviceInfo:1#GetInfo` & `urn:NETGEAR-ROUTER:service:WLANConfiguration:1#GetWPASecurityKeys` which are also fired by the IOs app. I'll create according Issues & provide Req/Res samples..

**Comment by gruijter** [comment]
@ArneCL I still have a problem to set the router to config mode. How is your investigation going?

**Comment by ArneCL** [comment]
@gruijter I was able to successfully test this functionality on a WNR2000v5 with firmware 1.0.0.28. I just added a simple implementation in the according feature-branch (still needs refactoring/formatting).

However, I was **not able to reproduce the errorcode 702** - even though the requests/responses I captured are the same as yours. Maybe you can check out that branch and see if the config-enable works for you? (I also provided a simple sample file...)

**Comment by gruijter** [comment]
I now have it working as well. Think I was in async-hell (I'm doing NodeJS, not Python).

I'm not sure yet, but it seems the set_config_mode and finish_config_mode are not really required. At least I can keep blocking and unblocking devices also after doing a successful finish_config

**Comment by caffeinatedMike** [comment]
@gruijter Any chance we can try implementing this into PyNetgear?

@matmaul Has there been any motion on this feature for PyNetgear?

**Comment by gruijter** [comment]
sure, I don't know why not. It has been working in my Homey app for a year, and it is actually the killer application for most users. I also use it to limit the screentime of my kids.

https://apps.athom.com/app/com.gruijter.netgear

**Comment by gruijter** [comment]
And for anyone that wants to try the functionality on node.js, I made a node package here: https://www.npmjs.com/package/netgear

To try from a pc:
// INSTRUCTIONS FOR TESTING FROM DESKTOP:
// install node (https://nodejs.org)
// install this package: > npm i netgear
// run the test (from the test folder): > node test yourpassword

**Comment by caffeinatedMike** [comment]
@gruijter As previously discussed on my other (now closed) issue I couldn't manage to get the nodejs module working. I'm afraid I can only be of help if I have a python version to test as I'm more knowledgeable in a python environment.

**Comment by caffeinatedMike** [comment]
@gruijter Are the `start_config` & `stop_config` requests actually needed to perform the blocking/unblocking? I just want to be clear before constructing an updated feature branch for people to test.

**Comment by caffeinatedMike** [comment]
@gruijter Could you test out my pull request (#50) to see if I have everything functioning correctly in the python version? I refactored a stale pull request to suit the new code base.

**Comment by gruijter** [comment]
@caffeinatedMike sure, if you tell me how to do that :) I downloaded python for windows. So now what do I do?

**Comment by caffeinatedMike** [comment]
@gruijter Ok, that'll be easy :)
Make sure you install python 3.7

1. Download my [dev branch](https://github.com/caffeinatedMike/pynetgear/tree/feature/updated-device-blocking) as a zip
2. Unzip folder to desktop
3. Navigate to inside the folder `pynetgear-feature-updated-device-blocking` & create a python script with the following code
   ```
   import netgear
   
   def test_block(pw, pt, macaddress):
       router = netgear.Netgear(password=pw, port=pt)
       block_result = router.allow_block_device(macaddress,'Block')
   
       if block_result:
           print('Device {0} blocked'.format(macaddress))
       else:
           print('Failed to block device {0}'.format(macaddress))
   
   def test_allow(pw, pt, macaddress):
       router = netgear.Netgear(password=pw, port=pt)
       block_result = router.allow_block_device(macaddress,'Allow')
   
       if block_result:
           print('Device {0} allowed/unblocked'.format(macaddress))
       else:
           print('Failed to allow/unblock device {0}'.format(macaddress))
   
   
   test_block('thisisthepassword', 'thisistheport', 'thisisthemacaddresstoblock')
   #test_allow('thisisthepassword', 'thisistheport', 'thisisthemacaddresstoallow')
   ```
   Obviously change the 3 parameter `thisisthepassword`, `thisistheport` and `thisisthemacaddresstoblock`

4. I have the `test_allow` function commented out because we need to test the block functionality first. After you save that script in the folder, right-click it > Open in IDLE
5. Press F5 to run the script (or hover over the Run menu & select Run Module)
6. If all goes well it should print `Device 01:ab:02:cd:03:ef blocked`
7. Test your device to see if the device you blocked is in fact successfully blocked.
8. Now, still in the idle, comment out `test_block` function call at the bottom of the script and uncomment the `test_allow` function call (these are found on the last two lines of the script)
9. If all goes well it should print `Device 01:ab:02:cd:03:ef allowed/unblocked`
10. Report back here with results

I tried to explain in as much detail as possible to hopefully make it easy for you :)

**Comment by gruijter** [comment]
Wow 😂. I think it will not be before tomorrow when I can try this. My son is having his birthday party tonight (Im on CET time, and you?)

**Comment by caffeinatedMike** [comment]
:laughing: No worries then! I'll be able to test when I get home. Tell your son Mr. Meeseeks says happy birthday for me! I'm on EST time.

**Comment by gruijter** [comment]
got a few minutes. trying now. but getting an error
Traceback (most recent call last):
  File "C:\Users\Public\Downloads\pynetgear-feature-updated-device-blocking\test_block_allow.py", line 1, in <module>
    import netgear
ModuleNotFoundError: No module named 'netgear'

so where do i place what to get the module?

**Comment by caffeinatedMike** [comment]
Since you have that script in the same directory as the `netgear` folder that import statement should work. Make sure there's a blank `__init__.py` in the directory of this script. If there is and it still gives that error maybe try changing the import statement to `from . import netgear` to see if that helps at all

**Comment by caffeinatedMike** [comment]
The directory structure should be:

pynetgear-feature....
   - `__init__.py` (blank file)
   - `test_block_allow.py`
   - netgear (folder)
      - `__init__.py`
      - `__main__.py`

**Comment by caffeinatedMike** [comment]
Run the setup.py file first. I just remember you're on a fresh python
install so we need to get you the dependencies first.

Best Regards,

Michael Hill

On Oct 19, 2018 1:28 PM, "gruijter" <notifications@github.com> wrote:

next error appears...
RESTART:
C:\Users\Public\Downloads\pynetgear-feature-updated-device-blocking\test_block_allow.py

Traceback (most recent call last):
File
"C:\Users\Public\Downloads\pynetgear-feature-updated-device-blocking\test_block_allow.py",
line 1, in
import pynetgear
File
"C:\Users\Public\Downloads\pynetgear-feature-updated-device-blocking\pynetgear_
*init*_.py", line 12, in
import requests
ModuleNotFoundError: No module named 'requests'

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MatMaul/pynetgear/issues/16#issuecomment-431437928>,
or mute
the thread

**Comment by gruijter** [comment]
setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

**Comment by caffeinatedMike** [comment]
Ok, just open requirements.txt and in a command prompt window `pip install {modulename}=={module version} for each requirement listed

**Comment by gruijter** [comment]
'pip' is not recognized as an internal or external command,
operable program or batch file.

I think I will leave at this for now :( Have to give my son some attention :)

**Comment by caffeinatedMike** [comment]
I'm guessing you didn't do a full python install then. No worries, I'll be home in a little bit to test. Have fun with you son :)

**Comment by MatMaul** [comment]
Once you have a setup with pip :
pip install -e .
python -m pynetgear test.py

**Comment by caffeinatedMike** [comment]
I'm home now @matmaul, but entertaining guests atm. Think you'll be able to test real quick? Would be awesome to get this included in the weekend release :)
