### ISSUE TITLE
Update PyPi version with get_traffic_meter capability

### ISSUE THREAD

**Issue by alcoolfire** [MatMaul/pynetgear#17]
Is it too early to request that the Python Package Index (PyPi) be updated with a version of pyNetgear that includes get_traffic_meter functionality? I've got a Netgear R8000 running the latest firmware and its traffic meter web UI is presenting data that is occasionally very obviously wrong (eg. monthly traffic temporarily decreasing instead of increasing). I'd like to see if pyNetgear extracts the same bad data with SOAP and perhaps figure out what's going wrong. I'm brand new to Python and have no familiarity with Git.

**Comment by gruijter** [comment]
@alcoolfire If you are more familiar with javascript you might want to check out this version: https://github.com/gruijter/netgear.js/

**Comment by ArneCL** [comment]
@alcoolfire 
I'll update the PyPi Version ASAP. 
With regards to the "misformatting" - it would be nice if you could capture the SOAP request/response for e.g. via  [How To Inspect IOs http-traffic](https://www.engadget.com/2011/02/21/how-to-inspect-ioss-http-traffic-without-spending-a-dime/)

**Comment by alcoolfire** [comment]
@ArneCL: I'm not sure what you mean by "misformatting". The only problem I'm currently aware of with the R8000 is that it reports bad traffic data in its built-in web UI traffic meter page (which I think is non-SOAP). I'm accessing the web UI manually from a desktop web browser, not the Netgear Genie app (which I've no interest in), so I don't yet know what will happen once I have the means to retrieve the data via SOAP with pyNetgear. FWIW, the bad data I refer to manifests with such absurdities as monthly traffic usage not being monotonic within the same month. For example, it will suddenly increase by 17GB during the day and then fall back by 14GB later the same day.  Another example is that the data for "Yesterday" will sometimes differ when read at different times in the same day. I want to use pyNetgear to pull the traffic meter data every 10 minutes or so over the course of multiple days to see if there is a pattern. It's possible, for example, that a pattern might suggest a time zone bug (ie. "yesterday" is wrongly UTC-based rather than the currently defined time zone). Of course, it's possible the SOAP API doesn't show the same problem, which would also be interesting. Once I can script something, I will try to capture the SOAP request/response.

**Comment by ArneCL** [comment]
@alcoolfire Sorry I got you wrong, so this is rather an Netgear-Firmware issue. 
Could you please specify what exactly you are expecting & what does not work?

- Do you experience any problems with pynetgear's get_traffic_meter() & your Netgear R8000?

You should make yourself familiar with python - a sample script might look like:
```python
from pynetgear import Netgear
netgear = Netgear("yourPassword", "yourHost", "yourUsername", port)

print(netgear.get_attached_devices())
```

**Comment by alcoolfire** [comment]
@ArneCL: Yes, the problem I'm trying to investigate is a bug in Netgear firmware, not in pyNetgear. In trying to use pyNetgear I realized the current version in PyPi does not actually include get_traffic_meter(), which is why I'm asking if you can release a new version to PyPi.

I expect that once I have a version of pyNetgear that includes get_traffic_meter() that it will give me the same kind of data as I am currently getting manually from the R8000 web UI, but it remains to be seen whether the Netgear firmware bug affects only the web UI or also the SOAP API. I will use this to automate periodic traffic data acquisition. If it were possible, I would like an additional function that would get the raw traffic data from the R8000 so that I could process it myself to avoid the Netgear firmware bug, but I have no idea if the router's SOAP API provides for that.

I have already tried get_attached_devices() with the R8000 running firmware version 1.0.3.46_1.1.32 and it seems to work, giving this sort of (sanitized) results:
```
Device(signal=7, ip='10.9.8.7', name='seven', mac='DE:AD:C0:DE:98:07', type='wired', link_rate=None)
Device(signal=None, ip='10.9.8.8, name='eight', mac='DE:AD:C0:DE:98:08', type='wired', link_rate=None)
Device(signal=None, ip='10.9.8.9', name='nine', mac='DE:AD:C0:DE:98:09', type='wired', link_rate=None)
Device(signal=None, ip='10.9.8.10', name='ten', mac='DE:AD:C0:DE:98:10', type='wireless', link_rate=72)
Device(signal=None, ip='10.9.8.11', name='eleven', mac='DE:AD:C0:DE:98:11', type='wireless', link_rate=72)
Device(signal=None, ip='10.9.8.12', name='twelve', mac='DE:AD:C0:DE:98:12', type='wireless', link_rate=58)
Device(signal=None, ip='10.9.8.13', name='thirteen', mac='DE:AD:C0:DE:98:13', type='wired', link_rate=None)
```

What does the "signal=" field refer to?

**Comment by ArneCL** [comment]
@alcoolfire You're right - the current PyPi version does not include the get_traffic_meter_function 🙈  this should be solved in the next days!

Don't worry to much to the current field-mapping, as this seems to have changed through Netgear firmware updates - see also  #15 for the upcoming mapping.

**Comment by alcoolfire** [comment]
@ArneCL: The _Readme.md_ file says that the Netgear SOAP API was discovered by reverse engineering the requests made by the NETGEAR Genie app. I downloaded the latest firmware ZIP file for the R8000 and extracted the CHK file for a closer look. I extracted the R8000 file system from it and learned that it includes a binary called `upnpd` in which one can find what I think is a long list of SOAP APIs (including the two pyNetgear supports). Am I really seeing 84 of them?!? It would be great to see pyNetgear enhanced to support many of those, but would it at least be possible to have `GetTrafficMeterOptionsResponse()` and `GetTimeZoneInfoResponse()` added? Those particular ones appear to return values for 'RestartHour', 'RestartMinute', 'RestartDay', 'NewTimeZone', and 'NewDaylightSaving', which are all relevant to understanding the traffic meter bug.

FWIW, the source code for the R8000 firmware that one can obtain from Netgear only includes `upnpd` as a prebuilt binary, so I assume it is closed source.

Since Github won't let me attach the list of SOAP APIs I extracted, here's the commands I used to get it:
```
$ binwalk -e /some/directory/R8000-V1.0.3.46_1.1.32.chk

DECIMAL         HEX             DESCRIPTION
-------------------------------------------------------------------------------------------------------
58              0x3A            TRX firmware header, little endian, header size: 28 bytes,  image size: 30220288 bytes, CRC32: 0x2FB1D9F flags/version: 0x10000
86              0x56            LZMA compressed data, properties: 0x5D, dictionary size: 65536 bytes, uncompressed size: 4982560 bytes
2015254         0x1EC016        PC bitmap, Windows 3.x format, 1868947562 x -1977679049 x 4487
WARNING: Extractor.execute failed to run '/opt/firmware-mod-kit/trunk/unsquashfs_all.sh '1EEE3E.squashfs'': [Errno 2] No such file or directory
2027070         0x1EEE3E        Squashfs filesystem, little endian, version 4.0, compression:  size: 28190080 bytes,  1538 inodes, blocksize: 131072 bytes, created: Wed Apr 26 20:49:55 2017

$ ls
1EEE3E.squashfs  56  56.7z

$ unsquashfs 1EEE3E.squashfs
Parallel unsquashfs: Using 4 processors
1436 inodes (1971 blocks) to write


write_xattr: could not write xattr security.selinux for file squashfs-root/bin/addgroup because you're not superuser!

write_xattr: to avoid this error message, either specify -user-xattrs, -no-xattrs, or run as superuser!

Further error messages of this type are suppressed!
[==========================================================================================================================================================================================================================-] 1971/1971 100%
created 1200 files
created 103 directories
created 235 symlinks
created 0 devices
created 0 fifos

$ ls
1EEE3E.squashfs  56  56.7z  squashfs-root/

$ grep -ar 'GetTrafficMeterStatisticsResponse' squashfs-root/
squashfs-root/usr/sbin/upnpd:    <m:GetTrafficMeterStatisticsResponse
squashfs-root/usr/sbin/upnpd:    </m:GetTrafficMeterStatisticsResponse>

$ strings -n 1 squashfs-root/usr/sbin/upnpd | sed -nre "/^<\?xml/{h;s/./=/g;x};H;\~</soap-env:Envelope>~{x;/^=+\n<\?xml.+<m:/p}" > r8000-soap.txt
```
If someone can tell me how to submit my _r8000-soap.txt_ file, I will do that. Examples:
```
<?xml version="1.0" encoding="UTF-8"?>
<soap-env:Envelope
        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"
        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
        >
<soap-env:Body>
    <m:GetTrafficMeterOptionsResponse
        xmlns:m="<%sa_service_type();%>">
        <NewControlOption><%getTrafficMeterOptions();%></NewControlOption>
        <NewMonthlyLimit><%getMonthlyLimit();%></NewMonthlyLimit>
        <RestartHour><%getRestartHour();%></RestartHour>
        <RestartMinute><%getRestartMinute();%></RestartMinute>
        <RestartDay><%getRestartDay();%></RestartDay>
    </m:GetTrafficMeterOptionsResponse>
    <ResponseCode><%sa_response_code();%></ResponseCode>
</soap-env:Body>
</soap-env:Envelope>
```
and
```
<?xml version="1.0" encoding="UTF-8"?>
<soap-env:Envelope
        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"
        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
        >
<soap-env:Body>
    <m:GetTimeZoneInfoResponse
        xmlns:m="<%sa_service_type();%>">
        <NewTimeZone><%time_zone();%></NewTimeZone>
        <NewDaylightSaving><%daylightsaving();%></NewDaylightSaving>
    </m:GetTimeZoneInfoResponse>
    <ResponseCode><%sa_response_code();%></ResponseCode>
</soap-env:Body>
</soap-env:Envelope>
```

**Comment by gruijter** [comment]
Good stuff 👍 
I think that the samples you posted are only the response messages from the router. Would be awesome to see the request posts as well!

Anyway, you can attach a file to this post simply by dragging and dropping. Or if it is too big you could maybe post a link to a public filesharing service.

**Comment by alcoolfire** [comment]
I've now attached what I extracted from the `upnpd` binary, I hope. I'm afraid the lack of request posts is because I haven't found them.

[r8000-soap.txt](https://github.com/balloob/pynetgear/files/1150902/r8000-soap.txt)

**Comment by gruijter** [comment]
Well, the download works for me :)

**Comment by ArneCL** [comment]
@alcoolfire Great Work! 
The Download works just fine for me - I think as a first step, we could use your little "howto" to get a collection of SOAP responses for different Router-Types. 

Regarding the feature-request: I'll See what I do/test on my Hardware (Now also got a WNR2200v5, which should support more of the Genie-Stuff...) and get back to you. Would be nice to have the functionalities tested in a RXXXX as well, before updating the PyPi Version. Ü

**Comment by deustis** [comment]
Seconding the request for a PyPI update here. Needed to pick up the fix for unknown device parsing [#15]. I've been running the latest unreleased pynetgear code without any problems. 👍 (WNDR3700)

**Comment by filcole** [comment]
Updated PyPI would be very welcome.  Bugs in the current PyPi version are causing issues for Homeassistant users on newer router firmware, see https://github.com/home-assistant/home-assistant/issues/11142.  Is there anything I can do to help?

**Comment by MatMaul** [comment]
@filcole Working on it.
What mentioned changes do you need to fix this ? the replace, the re.DOTALL or both ? it is not really clear to me from the thread.

**Comment by MatMaul** [comment]
ok I just read the doc of DOTALL, my guess is that the replace is enough since it removes any EOL, and DOTALL ignores them.

**Comment by MatMaul** [comment]
0.4.0 released with proper XML parsing instead of the regex.
