### ISSUE TITLE
Improvement: Catch exceptions for timeouts

### ISSUE THREAD

**Issue by ArneCL** [MatMaul/pynetgear#18]
With version 0.33, pynetgear does not differ between returnCodes or timeouts and e.g. throws an exception (`requests.exceptions.ConnectionError`) in case the router can't be accessed. See also [HA Issue 1988](https://github.com/home-assistant/home-assistant/issues/1988)

Expected: A comprehensive log-entry.

**Comment by starkillerOG** [comment]
A lot of improvements on error handeling have occurred since this issue.
Closing this, if you still experiance any issues, feel free to open a new issue.
