### ISSUE TITLE
Traffic Statistics endpoint has moved on Netgear M1 MR1100

### ISSUE THREAD

**Issue by TJC** [MatMaul/pynetgear#36]
I have a Netgear M1 MR1100.

The SOAP call to `urn:NETGEAR-ROUTER:service:ParentalControl:1#Authenticate` succeeds, and so does, for eg, `"urn:NETGEAR-ROUTER:service:DeviceInfo:1#GetAttachDevice`.

When I call `urn:NETGEAR-ROUTER:service:DeviceConfig:1#GetTrafficMeterStatistics` I get:
`501:Unsupported Action`

I don't suppose anyone knows where that has moved to?

**Comment by gruijter** [comment]
Did you perhaps not enable traffic statistics in the router?

**Comment by TJC** [comment]
If I log into the router via the web interface, I can see the traffic stats -- so I believe I have?

**Comment by MatMaul** [comment]
Can you see them in the Genie app ?

**Comment by TJC** [comment]
No, the Android genie app doesn't seem to be able to show traffic statistics either!

**Comment by gruijter** [comment]
So I guess its a bug in your router firmware then?

**Comment by TJC** [comment]
I don't know :(

Seems a bit like it, but then that's frustrating!

**Comment by TJC** [comment]
I have opened this query with Netgear:

https://community.netgear.com/t5/Mobile-Routers-Hotspots-Modems/M1-MR1100-traffic-stats-usage-data-SOAP-API-calls/m-p/1575300/

**Comment by MatMaul** [comment]
Closing for now, let us know if it get fixed on Netgear side one day...
