### ISSUE TITLE
pynetgear stopped working for WNR3500Lv2 router

### ISSUE THREAD

**Issue by etsinko** [MatMaul/pynetgear#37]
I recently noticed that my Home Assistant started showing me 'Error parsing xml response' error during start up of pynetgear. I did some digging and here what I found:
In commit b8c7ce474e7ce768c0365ac50db3eea596ca2bf3 a new parsing mechanism for response was introduced - now it is always parsed as XML. 

Unfortunately my router returns an XML with a typo in it. Pynetgear expects the node `GetAttachDeviceResponse` to have the `urn:NETGEAR-ROUTER:service:DeviceInfo:1` namespace while my router returns it as `urn:NETGEAT-ROUTER:service:DeviceInfo:1`. I updated my router to the latest firmware (V1.2.0.50_50.0.90) and it didn't solve the problem.

I'm not sure what the best solution for this problem could be. Do you think ditching namespaces altogether might fix this issue?

**Comment by etsinko** [comment]
Here is my XML response (I removed the text of `NewAttachDevice` node):
```
<?xml version="1.0" encoding="UTF-8"?>
<soap-env:Envelope
        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"
        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
        >
<soap-env:Body>
    <m:GetAttachDeviceResponse
        xmlns:m="urn:NETGEAT-ROUTER:service:DeviceInfo:1">
        <NewAttachDevice></NewAttachDevice>
    </m:GetAttachDeviceResponse>
    <ResponseCode>000</ResponseCode>
</soap-env:Body>
</soap-env:Envelope>
```

**Comment by MatMaul** [comment]
... what a failure. I'll see what can be done. They already have a recurring typo with true becoming ture on some routers...

**Comment by MatMaul** [comment]
https://stackoverflow.com/questions/4402310/how-to-ignore-namespace-when-selecting-xml-nodes-with-xpath

Can you try with `//*[local-name()='NewAttachDevice']` as the xpath to see ?
If it works I'll change it.
