### ISSUE TITLE
Timeout under home assistant

### ISSUE THREAD

**Issue by michaelblight** [MatMaul/pynetgear#38]
I have a D6200 on the latest firmware with 7 wired connections and about 20 wireless. Doesn't sound too onerous, but the NetGenie interface takes over 10 seconds to display. When I enabled it in Home Assistant, I get timeout errors more than once a minute (see below). It seems to find some of the devices but not all. I noticed the source to pynetgear has timeout=10 hardcoded. Could this be my problem, and should I be expecting better? pynetgear is running inside HA, inside Docker, inside VirtualBox on a PC wired to the D6200.

If I run
`python3 -m pynetgear <password> 192.168.0.1`
I get json output starting with "{'NewTodayConnectionTime':" and ending in "'NewLastMonthDownload': (0.0, 0.0)}", but all the values are zero. The json is then followed with the same timeout that HA gets. Any help would be much appreciated.

> Log Details (ERROR)
> Sat Jun 02 2018 14:09:38 GMT+1000 (Australian Eastern Standard Time)
> 
> Error talking to API
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 2, in raise_from
>   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
>     httplib_response = conn.getresponse()
>   File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
>     response.begin()
>   File "/usr/lib/python3.6/http/client.py", line 297, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "/usr/lib/python3.6/socket.py", line 586, in readinto
>     return self._sock.recv_into(b)
> socket.timeout: timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
>     timeout=timeout
>   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
>     raise value
>   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
>     chunked=chunked)
>   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
>     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
>   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
>     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
> urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.0.1', port=5000): Read timed out. (read timeout=10)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/pynetgear/__init__.py", line 236, in _make_request
>     data=message, timeout=10, verify=False)
>   File "/usr/lib/python3.6/site-packages/requests/api.py", line 112, in post
>     return request('post', url, data=data, json=json, **kwargs)
>   File "/usr/lib/python3.6/site-packages/requests/api.py", line 58, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 521, in send
>     raise ReadTimeout(e, request=request)
> requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.0.1', port=5000): Read timed out. (read timeout=10)
>

**Comment by dshokouhi** [comment]
I am also seeing this error on my Nighthawk X8, typically when this happens a device that is home get marked as not_home temporarily.

```2018-06-21 09:55:47 ERROR (SyncWorker_4) [pynetgear] Error talking to API
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/srv/homeassistant/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/srv/homeassistant/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/srv/homeassistant/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/srv/homeassistant/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/srv/homeassistant/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/srv/homeassistant/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/srv/homeassistant/lib/python3.6/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.1.1', port=5000): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/pynetgear/__init__.py", line 236, in _make_request
    data=message, timeout=10, verify=False)
  File "/srv/homeassistant/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/srv/homeassistant/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/srv/homeassistant/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/homeassistant/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/srv/homeassistant/lib/python3.6/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.1.1', port=5000): Read timed out. (read timeout=10)
2018-06-21 09:55:47 WARNING (SyncWorker_4) [homeassistant.components.device_tracker.netgear] Error scanning devices```

**Comment by MatMaul** [comment]
Let's increase to 1mn then. I just hope it doesn't lead to weird effects because I think the default delay between polling is 12s.

**Comment by MatMaul** [comment]
or 30s should be enough.

**Comment by michaelblight** [comment]
I'm keen to test. I did try changing the code myself, but I'm new to Python and Ubuntu. Despite making a change, when I tested it I still got "(read timeout=10)" in the error, so I assume whatever I did was wrong.

**Comment by michaelblight** [comment]
I tried modifying it myself again, and this time it worked. I just changed the two timeouts at lines 245 and 253 in __init__.py from 10 to 100. It ran successfully outside HA.

I have HA running inside Docker, and I'm struggling to understand how I get that version to update. Given that the error provides the path, and that's the file I'm editing, I would have thought a restart of HA would pick up that version, but no.

I noticed @MatMaul has changed the timeout to 30s, so I tried to update to this version, but I don't know how to do it properly so it didn't work. I used Portainer to connect to the HA Docker container and ran `pip3 install --upgrade pynetgear`, which did "stuff" but the error in HA showed timeout=10 again. And I upgraded HA to 0.72.1 using hassio but that didn't pull the newer version so it still timed out after 10 seconds.

Do you know how I can update the version in HA to test it works there?

**Comment by MatMaul** [comment]
A new version has not been released yet for pypi registry. In the meantime you can do:
`pip uninstall pynetgear`
`pip install git+https://github.com/MatMaul/pynetgear.git`

**Comment by michaelblight** [comment]
That works within the container until I restart HA. After a restart the original timeout is restored.

I'm not sure if HA retries after 12 minutes if it gets this error. I left it running for a while, and only one error shows up suggesting that either it only errored once or it stops retrying after the error. Since  my iPhone is on Wifi and shows up in Netgear Genie, but HA still thinks it is "not_home", it looks like it's not trying again. If this is the case, I can't test in within HA.

**Comment by MatMaul** [comment]
New version released, update sent to home-assistant.
https://github.com/home-assistant/home-assistant/pull/15768
