### ISSUE TITLE
Version 0.4.0 breaks compatability with WNDR4500

### ISSUE THREAD

**Issue by wieroo** [MatMaul/pynetgear#42]
Hello

I'm using pynetgear via home assistant, and a recent upgrade has resulted in a upgrade from pynetgear 0.3.3 to 0.4.0. This does not work on my WNDR4500.
```
$ pip3 install pynetgear=0.3.3
python3 -m pynetgear pass host user 
# works fine

$ pip3 install pynetgear=0.4.0
python3 -m pynetgear pass host user 
# Error parsing xml response: <?xml version="1.0" encoding="UTF-8"?>
```

I believe this is a bug.

Also see https://github.com/home-assistant/home-assistant/issues/14752

**Comment by MatMaul** [comment]
Please try again with 0.4.1, it has several bugfixes.
