### ISSUE TITLE
Unable to parse Netgear response with non-printable ASCII character: xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 6, column 245

### ISSUE THREAD

**Issue by zhaokoh** [MatMaul/pynetgear#46]
This issue is related to https://github.com/home-assistant/home-assistant/pull/15768 and #42.

After much investigation follow from the original issue reported by me and others in homeassistant and #42 version 0.78.3/0.79.0 of homeassistant that uses pynetgear 0.4.1 still have similar issue.

I have investigated further and the root cause of the issue seem to be dealing with non-printable ASCII character.

Specifically, if netgear router was unable to figure out the device name, in their xml response, it will contain some ^P character (data link character). Copy and paste from the terminal will not reveal the character, which explain why the previous issue reported cannot be reproduced. This character can only be revealed when printing the response straight to a file.

I have attached a sample response (with ^P (or DLE character)) for example.

Is it possible to filter out non-printable characters?

Here is a snippet of code that I temporarily implemented for work-around:

Under ```pynetgear/__init__.py```

```
import string
def _find_node(response, xpath):

    response = ''.join(filter(lambda x: x in string.printable, response)) # This is the line that I added (with import above)
    it = ET.iterparse(StringIO(response))
    # strip all namespaces
    for _, el in it:
        if '}' in el.tag:
            el.tag = el.tag.split('}', 1)[1]
    node = it.root.find(xpath)
    if node is None:
        _LOGGER.error("Error finding node in response: %s", response)
        return False, None

    return True, node
```

[sample.txt](https://github.com/MatMaul/pynetgear/files/2431168/sample.txt)

**Comment by MatMaul** [comment]
Awesome! Don't you want to send a pull request? Otherwise I'll commit it myself, let me know.

**Comment by MatMaul** [comment]
There is also a stackoverflow thread I posted on homeassistant bug that have a piece of code to remove all illegal XML characters, perhaps we should use that instead. I'll try it a bit later with your response example 🙂

**Comment by MatMaul** [comment]
https://stackoverflow.com/questions/1707890/fast-way-to-filter-illegal-xml-unicode-chars-in-python, second answer.

**Comment by MatMaul** [comment]
First answer sorry.

**Comment by MatMaul** [comment]
I just did it, can you check it works after doing that in homeassistant virtualenv (or by applying the last commit manually):
`pip uninstall pynetgear
pip install git+https://github.com/MatMaul/pynetgear.git`

If it works I'll bake a new minor release.

**Comment by zhaokoh** [comment]
Yup, it seems to work with this update

**Comment by MatMaul** [comment]
Fixed and released, home-assistant update sent.
