### ISSUE TITLE
Errors and warnings filling up logs (R7800)

### ISSUE THREAD

**Issue by BergAutomations** [MatMaul/pynetgear#52]
Hi

Thanks again for the good work.

After updating Home Assistant to 81 (from 80.3) my log is filling up... 
Raspberry Pi 3, Hassbian updated yesterday. Pynetgear 0.50.
Everything running perfectly before 81. Netgear R7800 running V1.0.2.60.

```
device_tracker:
  - platform: netgear
    host: 192.168.30.1
    username: me ;) 
    password: !secret router
    port: 80
    interval_seconds: 15
    consider_home: 180
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False
```

Besides the errors and warnings everything seems to work fine. Not sure what going on:
```
2018-10-27 15:42:16 WARNING (Thread-19) [pynetgear] Unauthorized response, let's login and retry...
2018-10-27 15:42:16 ERROR (Thread-19) [pynetgear] Invalid response
2018-10-27 15:42:16 ERROR (Thread-19) [pynetgear] Get attached devices failed
2018-10-27 15:42:16 WARNING (Thread-19) [homeassistant.components.device_tracker.netgear] Error scanning devices
```
(the same errors and warnings is coming up every hour or so)

A question: Will we be able to use allow_block_device in Home Assistant?

**Comment by gruijter** [comment]
I have noticed that the R7800 sometimes fails in giving a proper response to getAttachedDevices2, while doing getAttachedDevices (not v2!) will always produce a valif list, but with less information per attached device. I updated the router firmware this week, and it has improved since then.

**Comment by BergAutomations** [comment]
I updated from V1.0.2.58 to V1.0.2.60 yesterday to check if that was the problem. But it is still throwing the same errors and warnings every hour (same as  with V1.0.2.58).

While checking the log now I also found this one between the usual ones:
`
2018-10-27 16:06:31 ERROR (Thread-9) [pynetgear] Can't parse attached devices string`

**Comment by BergAutomations** [comment]
Same setup just 0.82 Hassbian.

The errors and warnings are back again...

**Comment by BergAutomations** [comment]
Testing branch v1-default now. Looking good so far 👍

**Comment by MatMaul** [comment]
Closing for now, please open a new one if you manage to get a devices string that can't get parsed.
