### ISSUE TITLE
Add Netgear Nighthawk M1100 support

### ISSUE THREAD

**Issue by fcadet01** [MatMaul/pynetgear#61]
Hello everyone,

Can you, please, add the support of the netgear Nighthawk M1100 mobile 4G router ?

**Comment by MatMaul** [comment]
Is it not working ? If not, do you have any logs ?

**Comment by fcadet01** [comment]
> 
> 
> Is it not working ? If not, do you have any logs ?

Sorry, It's my bad, I've inversed some parameters.

Now it work.
