### ISSUE TITLE
Reboot Router

### ISSUE THREAD

**Issue by abellavida** [MatMaul/pynetgear#69]
I was able to get Reboot to work, not very adept at github, so if you want to add to your __init__.py this works.  

    def reboot_router(self):
        """
        Reboot Router
        
        """
        _LOGGER.info("Reboot Router")

        success, response = self._make_request(SERVICE_DEVICE_CONFIG,
                                               "Reboot")

        print(response.text)

        if not success:
            _LOGGER.error("Reboot failed")
            return None

        success, node = _find_node(
            response.text,
            ".//Reboot")
        if not success:
            return None

Response - 
<?xml version="1.0" encoding="UTF-8"?>
<soap-env:Envelope
        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"
        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
       >
 <soap-env:Body>
    <m:RebootResponse
        xmlns:m="urn:NETGEAR-ROUTER:service:DeviceConfig:1">
    </m:RebootResponse>
    <ResponseCode>000</ResponseCode>
</soap-env:Body>
</soap-env:Envelope>

**Comment by MatMaul** [comment]
I am closing this since it should be added by #73 soon. Thanks for the infos.
