### ISSUE TITLE
Unexpected entry, likely due to space in device name

### ISSUE THREAD

**Issue by little-boots** [MatMaul/pynetgear#70]
It looks like there are parse errors related to having spaces in the device name.  I think my model (C7000-100NAS) supports the spaces, whereas others don't.  The get_attached_devices method is working for me until it encounters the first device with a space in the name ("Roku Premiere"), then no devices are listed beyond that IP.  The specific error I'm getting is: 

`Unexpected entry: ['16', '192.168.0.101', 'Roku Pre']`

Let me know if there's more information that would be helpful.  Thanks!

**Comment by MatMaul** [comment]
Should hopefully be fixed by #94.
