### ISSUE TITLE
Orbis are very slow to update with accurate list of connected devices

### ISSUE THREAD

**Issue by skarfacegc** [MatMaul/pynetgear#71]
I'm using pynetgear to pull presence information from my orbi APs  (running in AP mode through a ddwrt router).  Until recently it had been pretty reliable (some mis-reads but nothing terrible). A week or so after the firmware update the information pulled by pynetgear takes several hours to not ever updating presence information. The only reason I'm opening a bug here is that as soon as I access the orbis via the orbi app devices quickly move to their appropriate state when queried with pynetgear.

I don't know if there is an additional command that needs to be issued to force the update or not, but I figured I'd let you folks know.

Rebooting the orbi's makes things better for a while but it goes back to very lagged detection a few days later.

Nothing notable in pynetgear output.

This is undoubtedly caused by the recent orbi firmware update to 2.31.44, not sure if this is even something that can be fixed with pynetgear.

Willing to help debug.

Orbi details

Hardware Version | RBR20
Firmware Version | V2.3.1.44
pynetgear 0.5.2

**Comment by skarfacegc** [comment]
Ok after some further digging ... it _seems_ like the v2 API doesn't suffer from the same lag as the v1 API.

**Comment by djmcp** [comment]
I'm experiencing the same issue with my Orbi's w/ 0.5.2 on HA 0.92.1 - have been for the last month or so.  I forced pynetgear to use v2 login and didn't see much change.  How were you testing the v2 API @skarfacegc ?

**Comment by skarfacegc** [comment]
```

#!/usr/bin/env python3

from pynetgear import Netgear

netgear = Netgear(password='YOURPASSWORD')

for i in netgear.get_attached_devices_2():
    print(i)

```

Then I just ran the above script in a loop.  If you set `accesspoints:` in the HA config that'll force the pynetgear component to use the get_attached_devices_2 rather than get_attached_devices.  As I said it _seems_ to be working better ... not 100% sure though.  Also, I'm on .90.(?)  not sure if that would matter much at all.

**Comment by VincentMasselis** [comment]
I can confirm, on my configuration, adding `accesspoints:` speeds up home detection leaves from 1 hour to 5 minutes

**Comment by skarfacegc** [comment]
@MatMaul Not sure if there is something worth doing here or not.  Looks like the V1 API works, but the V2 API is much faster.  Closing.  Feelings won't be hurt if it's re-opened.
